### ISSUE TITLE
Optimize multi-theme token handling

### ISSUE THREAD

**Issue by acd02** [adevinta/spark#592]
Improve the handling of multiple themes in our system.

Currently, when multiple themes are declared, all tokens are duplicated `n` times (where `n` is the number of themes).

Instead, we should only add a token if its value is different between themes. In most cases, the only tokens that need updating are the color tokens, so there's no need to duplicate tokens like spacing.

For example:
```css
:root {
  colors-primary: blue;
  colors-secondary: red;
  space-sm: 2px;
  space-md: 4px;
}

[data-theme=dark] {
  colors-primary: white;
  colors-secondary: black;
  /* No need for space-sm and space-md since their values don't differ from the root theme */
}

[data-theme=other] {
  colors-primary: purple;
  colors-secondary: green;
  /* No need for space-sm and space-md since their values don't differ from the root theme */
}
```
